config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :subcategories
    resources :products
    resources :suppliers
    resources :users

    get 'restore_product',  to: 'products#restore',  as: :restore_product
    get 'restore_supplier', to: 'suppliers#restore', as: :restore_supplier

    get 'remove_characteristic', to: 'products#remove_characteristic', as: :remove_characteristic
    get 'remove_value',          to: 'products#remove_value',          as: :remove_value
  end

  get 'admin/home'

  get 'profile',     to: 'account#profile',     as: :profile
  get 'orders_list', to: 'account#orders_list', as: :orders_list
  get 'cart',        to: 'account#cart',        as: :cart

  get 'add_to_cart', to: 'cart#add_to_cart',    as: :add_to_cart

  get 'thanks_for_signing_up', to: 'dashboard#thanks_for_signing_up', as: :thanks_for_signing_up

  get    'remove_item_order', to: 'orders#remove_item',  as: :remove_item_order
  post   'add_item',          to: 'orders#add_item',     as: :add_item
  post   'send_order',        to: 'orders#send_order',   as: :send_order
  post   'resend_order',      to: 'orders#resend_order', as: :resend_order

  get 'search', to: 'products#search', as: :search

  resources :orders
  resources :subcategories, only: :show
  resources :products, only: :show

  devise_for :users, :controllers => { registrations: "registrations", passwords: "passwords", sessions: "sessions" }

  resource :carts, only: [ :update, :show, :destroy ] do
    member do
      put :remove_item
    end
  end

  root 'dashboard#home'
end

app/views/admin/_sidebar.html.haml
.col-xs-12.col-sm-4.col-md-3
  %ul.list-group
    %li.list-group-item
      = link_to admin_home_path do
        %h4
          .glyphicon.glyphicon-cog
          Admin
    %li.list-group-item
      = link_to admin_categories_path do
        .glyphicon.glyphicon-th-large
        Categories
    %li.list-group-item
      = link_to admin_subcategories_path do
        .glyphicon.glyphicon-th
        Subcategories
    %li.list-group-item
      = link_to admin_products_path do
        .glyphicon.glyphicon-picture
        Products
    /%li.list-group-item
    /  = link_to '#' do
    /    .glyphicon.glyphicon-shopping-cart
    /    Orders
    %li.list-group-item
      = link_to admin_suppliers_path do
        .glyphicon.glyphicon-home
        Suppliers
    %li.list-group-item
      = link_to admin_users_path do
        .glyphicon.glyphicon-user
        Users

app/views/admin/home.html.haml
= render 'partials/header'
= render 'admin/sidebar'
.col-xs-12.col-sm-8.col-md-8.col-lg-9
  %title Site Administration | Supply Admin
  .page-header
    %h1 Site Administration
  %ol.breadcrumb
    %li.active Dashboard
  %ul.nav.nav-tabs
    %li.icon.dashboard_root_link.active{:rel => "", :title => ""}
      %a.pjax{:href => "http://localhost:3000/admin/"}
        .glyphicon.glyphicon-home
        %span Dashboard
  %table.table.table-condensed.table-striped
    %thead
      %tr
        %th.shrink.model-name Model name
        %th.records Records
        %th.shrink.controls
    %tbody
      %tr.odd.link.category_links{"data-link" => "/admin/category"}
        %td.col-md-1.col-xs-1
          %span.show
            = link_to 'Categories', admin_categories_path, class: 'pjax'
        %td
          .active.progress.progress-striped.progress-info{:style => "margin-bottom:0px"}
            .animate-width-to.progress-bar.progress-bar-info{id: "cat-width", :style => "width: #{get_record_bar[0]*2}%;"}
              = @categories.count
              = hidden_field_tag :categories_count, @categories.count, id: "categories-bar"
        %td.links.col-md-1.col-xs-1
          %ul.inline.list-inline
            %li.icon.index_collection_link{:rel => "tooltip", :title => "List"}
              = link_to admin_categories_path do
                .glyphicon.glyphicon-list
            %li.icon.new_collection_link{:rel => "tooltip", :title => "Add new"}
              = link_to new_admin_category_path do
                .glyphicon.glyphicon-plus
      %tr.even.link.characteristic_links{"data-link" => "/admin/characteristic"}
        %td.col-md-1.col-xs-1
          %span.show
            = link_to 'Subcategories', admin_subcategories_path, class: 'pjax'
        %td
          .active.progress.progress-striped.progress-danger{:style => "margin-bottom:0px"}
            .animate-width-to.progress-bar.progress-bar-danger{id: "subcat-width", :style => "width: #{get_record_bar[1]*2}%;"}
              = @subcategories.count
              = hidden_field_tag :subcategories_count, @subcategories.count, id: "subcategories-bar"
        %td.links.col-md-1.col-xs-1
          %ul.inline.list-inline
            %li.icon.index_collection_link{:rel => "tooltip", :title => "List"}
              = link_to admin_subcategories_path do
                .glyphicon.glyphicon-list
            %li.icon.new_collection_link{:rel => "tooltip", :title => "Add new"}
              = link_to new_admin_subcategory_path do
                .glyphicon.glyphicon-plus
      %tr.odd.link.order_links{"data-link" => "/admin/order"}
        %td.col-md-1.col-xs-1
          %span.show
            = link_to 'Products', admin_products_path, class: 'pjax'
        %td
          .active.progress.progress-striped.progress-success{:style => "margin-bottom:0px"}
            .animate-width-to.progress-bar.progress-bar-success{id: "prod-width", :style => "width: #{get_record_bar[2]/2}%;"}
              = @products.count
              = hidden_field_tag :products_count, @products.count, id: "products-bar"
        %td.links.col-md-1.col-xs-1
          %ul.inline.list-inline
            %li.icon.index_collection_link{:rel => "tooltip", :title => "List"}
              = link_to admin_products_path do
                .glyphicon.glyphicon-list
            %li.icon.new_collection_link{:rel => "tooltip", :title => "Add new"}
              = link_to new_admin_product_path do
                .glyphicon.glyphicon-plus
      /%tr.even.link.order_item_links{"data-link" => "/admin/order_item"}
      /  %td.col-md-1.col-xs-1
      /    %span.show
      /      %a.pjax{:href => "http://localhost:3000/admin/order_item"} Orders
      /  %td
      /    .active.progress.progress-striped.progress-success{:style => "margin-bottom:0px"}
      /      .animate-width-to.progress-bar.progress-bar-success{id: "ord-width", :style => "width: #{get_record_bar[3]*2}%;"}
      /        = @orders.count
      /        = hidden_field_tag :orders_count, @orders.count, id: "orders-bar"
      /  %td.links.col-md-1.col-xs-1
      /    %ul.inline.list-inline
      /      %li.icon.index_collection_link{:rel => "tooltip", :title => "List"}
      /        = link_to '#' do
      /          .glyphicon.glyphicon-list
      /      /%li.icon.new_collection_link{:rel => "tooltip", :title => "Add new"}
      /      /  = link_to '#' do
      /      /    .glyphicon.glyphicon-plus
      %tr.odd.link.order_status_links{"data-link" => "/admin/order_status"}
        %td.col-md-1.col-xs-1
          %span.show
            = link_to 'Suppliers', admin_suppliers_path, class: "pjax"
        %td
          .active.progress.progress-striped.progress-info{:style => "margin-bottom:0px"}
            .animate-width-to.progress-bar.progress-bar-info{id: "sup-width", :style => "width: #{get_record_bar[4]*3}%;"}
              = @suppliers.count
              = hidden_field_tag :suppliers_count, @suppliers.count, id: "suppliers-bar"
        %td.links.col-md-1.col-xs-1
          %ul.inline.list-inline
            %li.icon.index_collection_link{:rel => "tooltip", :title => "List"}
              = link_to admin_suppliers_path do
                .glyphicon.glyphicon-list
            %li.icon.new_collection_link{:rel => "tooltip", :title => "Add new"}
              = link_to new_admin_supplier_path do
                .glyphicon.glyphicon-plus
      %tr.even.link.product_links{"data-link" => "/admin/product"}
        %td.col-md-1.col-xs-1
          %span.show
            = link_to 'Users', admin_users_path, class: 'pjax'
        %td
          .active.progress.progress-striped.progress-warning{:style => "margin-bottom:0px"}
            .animate-width-to.progress-bar.progress-bar-warning{id: "usr-width", :style => "width: #{get_record_bar[5]*3}%;"}
              = @users.count
              = hidden_field_tag :users_count, @users.count, id: "users-bar"
        %td.links.col-md-1.col-xs-1
          %ul.inline.list-inline
            %li.icon.index_collection_link{:rel => "tooltip", :title => "List"}
              = link_to admin_users_path do
                .glyphicon.glyphicon-list
            /%li.icon.new_collection_link{:rel => "tooltip", :title => "Add new"}
            /  = link_to new_admin_user_path do
            /    .glyphicon.glyphicon-plus
      