config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :subcategories
    resources :products
    resources :suppliers
    resources :users

    get 'restore_product',  to: 'products#restore',  as: :restore_product
    get 'restore_supplier', to: 'suppliers#restore', as: :restore_supplier

    get 'remove_characteristic', to: 'products#remove_characteristic', as: :remove_characteristic
    get 'remove_value',          to: 'products#remove_value',          as: :remove_value
  end

  get 'admin/home'

  get 'profile',     to: 'account#profile',     as: :profile
  get 'orders_list', to: 'account#orders_list', as: :orders_list
  get 'cart',        to: 'account#cart',        as: :cart

  get 'add_to_cart', to: 'cart#add_to_cart',    as: :add_to_cart

  get 'thanks_for_signing_up', to: 'dashboard#thanks_for_signing_up', as: :thanks_for_signing_up

  get    'remove_item_order', to: 'orders#remove_item',  as: :remove_item_order
  post   'add_item',          to: 'orders#add_item',     as: :add_item
  post   'send_order',        to: 'orders#send_order',   as: :send_order
  post   'resend_order',      to: 'orders#resend_order', as: :resend_order

  get 'search', to: 'products#search', as: :search

  resources :orders
  resources :subcategories, only: :show
  resources :products, only: :show

  devise_for :users, :controllers => { registrations: "registrations", passwords: "passwords", sessions: "sessions" }

  resource :carts, only: [ :update, :show, :destroy ] do
    member do
      put :remove_item
    end
  end

  root 'dashboard#home'
end

app/views/partials/_header.html.haml
%header
  - if current_user
    %nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Supply", root_path, class: 'navbar-brand'

        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{ class: "#{ 'active' if (controller_name == 'dashboard') && (action_name == 'home')}" }
              = link_to root_path do
                %span.glyphicon.glyphicon-th{"aria-hidden" => "true"}
                Catalog
            /%li{ class: "#{ 'active' if action_name == 'favorites'}" }
            /  %a{:href => "#"}
            /    %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
            /    Favorites
            - if current_user && (current_user.has_role? :admin or current_user.has_role? :manager)
              %li{ class: "#{ 'active' if action_name == 'index'}" }
                = link_to orders_path do
                  %span.glyphicon.glyphicon-list{"aria-hidden" => "true"}
                  Orders
              %li{ class: "#{ 'active' if controller_name == 'admin'}" }
                = link_to admin_home_path do
                  %span.glyphicon.glyphicon-cog{"aria-hidden" => "true"}
                  Admin
          %ul.nav.navbar-nav.navbar-right
            %li
              = form_tag(search_path, method: :get, id: 'search', class: 'navbar-form navbar-left') do
                .form-group
                  = text_field_tag :search, '', placeholder: "Search", class: 'form-control'
                %button.btn.btn-default{:type => "submit"}
                  .glyphicon.glyphicon-search
            %li{ class: "#{ 'active' if action_name == 'cart'}" }
              = link_to cart_path do
                %span.glyphicon.glyphicon-shopping-cart{"aria-hidden" => "true"}
                Cart
                - if current_cart.count
                  %span.badge
                    = current_cart.count
            %li.dropdown{ class: "#{ 'active' if action_name == 'profile' or action_name == 'orders_list'}" }
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                %span.glyphicon.glyphicon-user{"aria-hidden" => "true"}
                #{current_user.first_name} #{current_user.last_name}
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to profile_path do
                    %span.glyphicon.glyphicon-user{"aria-hidden" => "true"}
                    Profile
                %li
                  = link_to orders_list_path do
                    %span.glyphicon.glyphicon-list{"aria-hidden" => "true"}
                    My List
                %li
                  %a{'data-target' => "#signOutModal", :role => "button", 'data-toggle' => :modal}
                    %span.glyphicon.glyphicon-off{"aria-hidden" => "true"}
                    Sign Out
  - else
    %nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
      .container-fluid
        = link_to "Supply", root_path, class: 'navbar-brand'
        .pull-right
          = link_to "Sign Up", new_user_registration_path, class: 'btn btn-success navbar-btn'
          = link_to "Login", new_user_session_path, class: 'btn btn-default navbar-btn'

#signOutModal.modal.fade{:role => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Sign Out
      .modal-body
        %h2.text-center
          %span.glyphicon.glyphicon-off{"aria-hidden" => "true", style: 'color: #C9302C'}
          %br/
          Do you really want sign out?
      .modal-footer
        %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} No
        = link_to 'Yes', destroy_user_session_path, :method => :delete, class: 'btn btn-success', id: 'signOutFakeBtn'