config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :subcategories
    resources :products
    resources :suppliers
    resources :users

    get 'restore_product',  to: 'products#restore',  as: :restore_product
    get 'restore_supplier', to: 'suppliers#restore', as: :restore_supplier

    get 'remove_characteristic', to: 'products#remove_characteristic', as: :remove_characteristic
    get 'remove_value',          to: 'products#remove_value',          as: :remove_value
  end

  get 'admin/home'

  get 'profile',     to: 'account#profile',     as: :profile
  get 'orders_list', to: 'account#orders_list', as: :orders_list
  get 'cart',        to: 'account#cart',        as: :cart

  get 'add_to_cart', to: 'cart#add_to_cart',    as: :add_to_cart

  get 'thanks_for_signing_up', to: 'dashboard#thanks_for_signing_up', as: :thanks_for_signing_up

  get    'remove_item_order', to: 'orders#remove_item',  as: :remove_item_order
  post   'add_item',          to: 'orders#add_item',     as: :add_item
  post   'send_order',        to: 'orders#send_order',   as: :send_order
  post   'resend_order',      to: 'orders#resend_order', as: :resend_order

  get 'search', to: 'products#search', as: :search

  resources :orders
  resources :subcategories, only: :show
  resources :products, only: :show

  devise_for :users, :controllers => { registrations: "registrations", passwords: "passwords", sessions: "sessions" }

  resource :carts, only: [ :update, :show, :destroy ] do
    member do
      put :remove_item
    end
  end

  root 'dashboard#home'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_status
  has_many :order_items, dependent: :destroy

  validates :order_status_id, :presence => { :message => 'parameter values are not valid'}
  validates :user_id,         :presence => { :message => 'parameter values are not valid'}

  before_validation :set_order_status

  def self.create_and_change(params)
    order = create(user_id: params[:user].id, address: params[:address], message: params[:message])

    params[:cart].items.each do |cart|
      cart.each do |cart_item|
        quantity = params[:items]["product_id_#{cart_item.id}#{cart_item.current_item(params[:cart])}"]
        characteristics = cart_item.characteristics

        order.order_items.create(product_id:      cart_item.product.id,
                                 quantity:        quantity,
                                 characteristics: characteristics)
      end
    end
    order
  end

  def self.create_or_update_items product, quantity, order, characteristics
    item = OrderItem.get_item_with_params(order.id, product.id, characteristics)
    if item[0]
      quantity = item[0].quantity.to_i + quantity.to_i
      item[0].update_attribute(:quantity, quantity)
    else
      order.order_items.create(product_id: product.id, quantity: quantity, characteristics: characteristics)
    end
  end

  def self.check_order_status_after_send order
    case order.order_items.map(&:sended).uniq.join(',').to_s
      when 'true,false'
        OrderStatus.find_by_name('Half handled')
      when 'false,true'
        OrderStatus.find_by_name('Half handled')
      when 'true'
        OrderStatus.find_by_name('Handled')
      else
        OrderStatus.find_by_name('New')
      end
  end

  private
	  def set_order_status
	    self.order_status_id ||= 1
	  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :send_order, :resend_order]
  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html
      format.json { render json: OrderDatatable.new(view_context) }
    end
  end

  def show
    @suppliers = Supplier.get_suppliers @order.order_items
    @products  = Product.where(remove: false).all
    @product   = Product.where(remove: false).find(params[:product_id]) if params[:product_id]
  end

  def create
    @order = Order.create_and_change(cart:    current_cart,
                                     user:    current_user,
                                     items:   params[:items],
                                     address: params[:address],
                                     message: params[:message])

    NotificationsMailer.create_order_user(@order).deliver
    User.all.each do |u|
      if u.active_account == true
        if u.has_role? :admin or u.has_role? :manager
          NotificationsMailer.create_order_admin(@order, u).deliver
        end
      end
    end

    if @order.valid?
      session[:cart] = current_cart.destroy(current_user)
      redirect_to root_path(order: 'create'),
        :notice => "Order submitted!"
    else
      redirect_to cart_path, :notice => "Checkout failed."
    end
  end

  def remove_item
    @order_item = OrderItem.find(params[:item_id])
    @order = @order_item.order
    @order_item.destroy
    status = Order.check_order_status_after_send(@order)
    @order.update_attribute(:order_status_id, status.id)
    redirect_to :back
  end

  def add_item
    order           = Order.find(params[:order_id])
    product         = Product.find(params[:product_id])
    quantity        = params[:quantity]
    characteristics = Characteristic.get_characteristics(params[:characteristics])
    Order.create_or_update_items(product, quantity, order, characteristics) if product && order && characteristics
    redirect_to :back
  end

  def send_order
    params[:items].split(' ').each do |i|
      OrderItem.update_quantity(i, params["item_id_#{i}"])
      OrderItem.update_sended_status(i)
      OrderItem.update_sended_date(i)
    end
    status = Order.check_order_status_after_send(@order)
    @order.update_attribute(:order_status_id, status.id)
    NotificationsMailer.send_order_supplier(params[:address], params[:items], params[:supplier_id], @order.user).deliver
    if params[:other_email].present?
      emails = params[:other_email].to_s.gsub(' ','').split(',')
      emails.each do |e|
        NotificationsMailer.send_order_other_email(params[:address], params[:items], params[:supplier_id], @order.user, e).deliver
      end
    end
    redirect_to :back
  end

  def resend_order
    NotificationsMailer.send_order_supplier(params[:address], params[:items], params[:supplier_id], @order.user).deliver
    if params[:other_email].present?
      emails = params[:other_email].to_s.gsub(' ','').split(',')
      emails.each do |e|
        NotificationsMailer.send_order_other_email(params[:address], params[:items], params[:supplier_id], @order.user, e).deliver
      end
    end
    redirect_to :back
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def quantity_of_products order
    quantity = 0
    order.order_items.each do |oi|
      quantity = quantity + oi.quantity
    end
    return quantity
  end
end

app/views/orders/_add_new_item.html.haml
/ Modal
#myModal.modal.fade{:role => "dialog"}
  .modal-dialog
    / Modal content
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Add new Item to Order
      .modal-body
        .well
          .col-xs-12.col-sm-12.col-md-12
            %label Select Product
            #select-new-product= select_tag :product, options_for_select(@products.collect{ |p| [p.name.to_s, p.id]}), id: 'add_product', style: 'width: 100%'
          .clearfix
          %br
          #select-caharacteristict
          .clearfix

      .modal-footer
        %button.btn.btn-primary#add-item-button{:disabled => "disabled"} Add
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
- @products.each do |p|
  = hidden_field_tag "image[value_#{p.id}]", p.photo.url, id: "image_#{p.id}"

app/views/orders/_order_info.html.haml
.well
  .col-xs-12.col-sm-3.col-md-3
    .rounded
      Deliver to:
      %textarea#deliver-to-address.form-control{:rows => "4", disabled: @order.order_status.name != 'New'}= @order.address
    %br
    .rounded
      To send also to:
      .lead
        %input#other-email.form-control{type: "email"}
        %h5.text-danger.hide{id: 'separate-emails'} Separate the e-mails with comma!
  .col-xs-12.col-sm-3.col-md-3
    .rounded
      Сustomer:
      %p
        .lead
          #{@order.user.first_name}
          #{@order.user.last_name}
        #{@order.user.email}
        %br
        #{@order.user.phone}
  .col-xs-12.col-sm-3.col-md-3
    .rounded
      Status:
      %p.lead
        %span.label{ class: get_color_status(@order.order_status_id)} #{@order.order_status.name}
    - if @order.message
      .rounded
        Message:
        %p.text-muted
          %span= @order.message
  .col-xs-12.col-sm-3.col-md-3
    .rounded
      Suppliers:
      - @suppliers.each_with_index do |s, i|
        %p.lead
          %a{href: "##{i.to_s + s.name}"}
            %span.black-link
              - @order_items = get_order_item(@order, s)
              - if check_items(@order_items) == 'false'
                #{s.name}
                %i.fa.fa-circle-o
              - elsif check_items(@order_items) == 'true'
                #{s.name}
                %i.fa.fa-check-circle-o.green-check
              - else
                - if get_not_sended_order_items(@order_items)
                  #{s.name} (Additional Order)
                  %i.fa.fa-circle-o
                - if get_sended_order_items(@order_items)
                  #{s.name}
                  %i.fa.fa-check-circle-o.green-check

      - if @order.order_status.name != 'Handled'
        %button.btn.btn-primary.btn{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"} Add new Item to Order
  .clearfix

app/views/orders/_select_new_product.html.haml
= form_tag(add_item_path, method: :post, id: 'add-new-item') do
  = hidden_field_tag :order_id, @order.id
  = hidden_field_tag :product_id, @product.id
  .col-xs-8.col-sm-8.col-md-8
    - @product.characteristics.each do |c|
      %label= c.name
      = select_tag "characteristics[#{c.id}]", options_from_collection_for_select(c.values, "id", "name"), class: 'form-control'
      %br
  .col-xs-4
    %label Count
    = number_field_tag :quantity, '1', min: 1, class: 'form-control'
    %br
    = image_tag @product.photo.url, height: "80", width: "80"

app/views/orders/index.html.haml
.col-xs-12.col-md-12
  %ol.breadcrumb
    %li.active Orders List
  .row
    .col-xs-12.col-md-12
      .table-responsive
        %table#orders-table.table.orders-list_table
          %thead
            %tr
              %th Order ID
              %th User
              %th Date
              %th Status
              %th

app/views/orders/show.html.haml
.col-xs-12.col-md-12
  = render 'orders/order_info'
  .row
    .col-xs-12.col-md-12
      - @suppliers.each_with_index do |s, i|
        - @order_items = get_order_item(@order, s)
        - if check_items(@order_items) == 'false'
          %span{id: i.to_s + s.name}
          = form_tag(send_order_path, method: :post, id: s.name) do
            = hidden_field_tag :address, @order.address, class: 'form-control', id: 'hidden-address'
            = hidden_field_tag :other_email, '', class: 'form-control', id: 'hidden-other-email'
            = hidden_field_tag :supplier_id, s.id
            = hidden_field_tag :items, @order_items.map(&:id)
            = hidden_field_tag :id, @order.id
            %ol.breadcrumb.supplier-header
              %span.text-left{id: "#supplier_#{s.id}"}= s.name
              %span.pull-right= submit_tag 'Send this order', class: 'btn btn-primary'
            .table-responsive
              %table.table
                %thead
                  %tr
                    %th Photo
                    %th Name / Link
                    %th Count
                    %th Actions
                %tbody
                  - @order_items.each do |i|
                    %tr
                      %td.col-md-1.col-xs-1
                        = image_tag i.product.photo(:thumb), class: 'img-rounded'
                      %td.col-md-2.col-xs-2.space-normal
                        %b
                          = link_to i.product.name, product_path(i.product)
                          - eval(i.characteristics).each do |k, v|
                            .small.text-normal= "#{k}: #{v}"
                      %td.col-md-4.col-xs-1
                        = number_field_tag "item_id_#{i.id}", i.quantity, min: '1', class: 'form-control width-90'
                      %td.col-md-1.col-xs-1
                        = link_to remove_item_order_path(item_id: i.id), confirm: 'confirm' do
                          .btn.btn-danger
                            .glyphicon.glyphicon-trash
        - elsif check_items(@order_items) == 'true'
          %span{id: i.to_s + s.name}
          %ol.breadcrumb.supplier-header
            %span.text-left= s.name
            %span.pull-right
              = form_tag(resend_order_path, method: :post, id: s.name) do
                = hidden_field_tag :address, @order.address, class: 'form-control', id: 'hidden-resend-address'
                = hidden_field_tag :other_email, '', class: 'form-control', id: 'hidden-resend-other-email'
                = hidden_field_tag :supplier_id, s.id
                = hidden_field_tag :items, @order_items.map(&:id)
                = hidden_field_tag :id, @order.id
                %button.btn.btn-success.resend-button{:type => "submit"} Resend
            %span.pull-right Sent: #{get_date_sended(@order_items).strftime('%m.%d.%y  %H:%M:%S')}
          .table-responsive
            %table.table
              %thead
                %tr
                  %th Photo
                  %th Name / Link
                  %th Count
                  %th
              %tbody
                - @order_items.each do |i|
                  %tr
                    %td.col-md-1.col-xs-1
                      = image_tag i.product.photo(:thumb), class: 'img-rounded'
                    %td.col-md-2.col-xs-2.space-normal
                      %b
                        = link_to i.product.name, product_path(i.product)
                        - eval(i.characteristics).each do |k, v|
                          .small.text-normal= "#{k}: #{v}"
                    %td.col-md-4.col-xs-1
                      = number_field_tag "item_id_#{i.id}", i.quantity, min: '1', class: 'form-control width-90', disabled: true
                    %td.col-md-1.col-xs-1
        - else
          - @not_sended_order_items = get_not_sended_order_items(@order_items)
          %span{id: i.to_s + s.name}
          = form_tag(send_order_path, method: :post, id: s.name) do
            = hidden_field_tag :address, @order.address, class: 'form-control', id: 'hidden-address'
            = hidden_field_tag :supplier_id, s.id
            = hidden_field_tag :items, @not_sended_order_items.map(&:id)
            = hidden_field_tag :id, @order.id
            %ol.breadcrumb.supplier-header
              %span.text-left{id: "#supplier_#{s.id}"}= "#{s.name} (Additional Order)"
              %span.pull-right= submit_tag 'Send this order', class: 'btn btn-primary'
            .table-responsive
              %table.table
                %thead
                  %tr
                    %th Photo
                    %th Name / Link
                    %th Count
                    %th Actions
                %tbody
                  - @not_sended_order_items.each do |i|
                    %tr
                      %td.col-md-1.col-xs-1
                        = image_tag i.product.photo(:thumb), class: 'img-rounded'
                      %td.col-md-2.col-xs-2.space-normal
                        %b
                          = link_to i.product.name, product_path(i.product)
                          - eval(i.characteristics).each do |k, v|
                            .small.text-normal= "#{k}: #{v}"
                      %td.col-md-4.col-xs-1
                        = number_field_tag "item_id_#{i.id}", i.quantity, min: '1', class: 'form-control width-90'
                      %td.col-md-1.col-xs-1
                        = link_to remove_item_order_path(item_id: i.id), confirm: 'confirm' do
                          .btn.btn-danger
                            .glyphicon.glyphicon-trash
          - @sended_order_items = get_sended_order_items(@order_items)
          %span{id: i.to_s + s.name}
          %ol.breadcrumb.supplier-header
            %span.text-left= s.name
            %span.pull-right Sent: #{get_date_sended(@sended_order_items).strftime('%m.%d.%y  %H:%M:%S')}
          .table-responsive
            %table.table
              %thead
                %tr
                  %th Photo
                  %th Name / Link
                  %th Count
                  %th
              %tbody
                - @sended_order_items.each do |i|
                  %tr
                    %td.col-md-1.col-xs-1
                      = image_tag i.product.photo(:thumb), class: 'img-rounded'
                    %td.col-md-2.col-xs-2.space-normal
                      %b
                        = link_to i.product.name, product_path(i.product)
                        - eval(i.characteristics).each do |k, v|
                          .small.text-normal= "#{k}: #{v}"
                    %td.col-md-4.col-xs-1
                      = number_field_tag "item_id_#{i.id}", i.quantity, min: '1', class: 'form-control width-90', disabled: true
                    %td.col-md-1.col-xs-1
= render 'orders/add_new_item'

app/views/orders/show.js.erb
$('#select-caharacteristict').html("<%= escape_javascript(render 'orders/select_new_product') %>");