config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :subcategories
    resources :products
    resources :suppliers
    resources :users

    get 'restore_product',  to: 'products#restore',  as: :restore_product
    get 'restore_supplier', to: 'suppliers#restore', as: :restore_supplier

    get 'remove_characteristic', to: 'products#remove_characteristic', as: :remove_characteristic
    get 'remove_value',          to: 'products#remove_value',          as: :remove_value
  end

  get 'admin/home'

  get 'profile',     to: 'account#profile',     as: :profile
  get 'orders_list', to: 'account#orders_list', as: :orders_list
  get 'cart',        to: 'account#cart',        as: :cart

  get 'add_to_cart', to: 'cart#add_to_cart',    as: :add_to_cart

  get 'thanks_for_signing_up', to: 'dashboard#thanks_for_signing_up', as: :thanks_for_signing_up

  get    'remove_item_order', to: 'orders#remove_item',  as: :remove_item_order
  post   'add_item',          to: 'orders#add_item',     as: :add_item
  post   'send_order',        to: 'orders#send_order',   as: :send_order
  post   'resend_order',      to: 'orders#resend_order', as: :resend_order

  get 'search', to: 'products#search', as: :search

  resources :orders
  resources :subcategories, only: :show
  resources :products, only: :show

  devise_for :users, :controllers => { registrations: "registrations", passwords: "passwords", sessions: "sessions" }

  resource :carts, only: [ :update, :show, :destroy ] do
    member do
      put :remove_item
    end
  end

  root 'dashboard#home'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :subcategory
  belongs_to :supplier
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/img/noimage.jpg"
  has_many :order_items
  has_many :characteristics, dependent: :destroy

  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates :name, presence: true
  validates :measurement, presence: true

  def self.create_characteristics product, characteristics, values
    if characteristics != nil
    	characteristics.each do |key_c, value_c|
        if (value_c != '') && (value_c != nil)
      		value_arr = []
      	  values.each do |key_v, value_v|
      	  	if key_c == key_v.split('_')[0]
      	  		value_arr.push(value_v)
      	  	end
      	  end
      	  characteristic = Characteristic.create(name: value_c, product_id: product.id) if value_arr.count > 0
      	  value_arr.each do |v|
            if (v != '') && (v != nil)
      	  	  Value.create(name: v, characteristic_id: characteristic.id)
            end
      	  end
          characteristic.destroy unless characteristic.values.any?
        end
    	end
    end
  end

  def self.update_characteristics product, characteristics, values
    if characteristics != nil
      characteristics.each do |key_c, value_c|
        characteristic = Characteristic.find_by_id(key_c)
        characteristic.update_attribute(:name, value_c) if characteristic
      end
      values.each do |key_v, value_v|
        value = Value.find_by_id(key_v)
        value.update_attribute(:name, value_v) if value
      end
      characteristics.each do |key_c, value_c|
        c = Characteristic.find_by_id(key_c)
        if c
          c.destroy unless c.values.any?
        end
      end
    end
  end

  def self.remove_products_by_supplier supplier
    supplier.products.each do |p|
      p.update_attribute(:remove, true)
    end
  end

  def self.search_product search
    where("LOWER(name) LIKE LOWER(?)", "%#{search}%") 
    where("LOWER(description) LIKE LOWER(?)", "%#{search}%")
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :restore]

  load_and_authorize_resource
  respond_to :html

  def index
    respond_to do |format|
      format.html
      format.json { render json: Admin::ProductsDatatable.new(view_context) }
    end
  end

  def show
    respond_with(@product)
  end

  def new
    @subcategories = Subcategory.all
    @suppliers     = Supplier.all
    respond_with(@product)
  end

  def edit
    @subcategories = Subcategory.all
    @suppliers     = Supplier.all
  end

  def create
    @product = Product.new(product_params)
    @product.save
    Product.create_characteristics(@product, params['characteristic'], params['value'])
    redirect_to admin_product_path(@product.id)
  end

  def update
    @product.update(product_params)
    Product.create_characteristics(@product, params['characteristic'], params['value'])
    Product.update_characteristics(@product, params['edit_characteristic'], params['edit_value'])
    redirect_to edit_admin_product_path(@product.id)
  end

  def remove_characteristic
    @characteristic = Characteristic.find(params[:characteristic_id])
    @characteristic.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def remove_value
    Value.find(params[:value_id]).destroy
    redirect_to :back
  end

  def destroy
    @product.update_attribute(:remove, true)
    redirect_to admin_products_path
  end

  def restore
    @product.update_attribute(:remove, false)
    redirect_to admin_products_path
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :photo, :measurement, :subcategory_id, :supplier_id, :description)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: :show

  def show
  	if @product.remove == true
  	  redirect_to :back
  	end
  end

  def search
    @products = Product.search_product(params[:search])
    @products = @products.page(params[:page]).per(12)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
	def get_characteristics characteristics
		char = []
    characteristics.each do |c|
      if characteristic = Characteristic.find(c)
        char.push(characteristic)
      end
    end
    return char
	end

	def get_values values
		val = []
    values.each do |v|
      if values = Value.find(v)
        val.push(values)
      end
    end
    return val
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.haml
= render 'partials/header'
= render 'admin/sidebar'
.col-xs-12.col-sm-8.col-md-8.col-lg-9   
  .content{"data-pjax-container" => ""}
    .page-header
      %h1 Edit Product #{@product.name}
    %ol.breadcrumb
      %li.false
        = link_to 'Dashboard', admin_home_path, class: 'pjax'
      %li.false
        = link_to 'Products', admin_products_path, class: 'pjax'
      %li.false
        = link_to @product.name, admin_product_path(@product.id), class: 'pjax'
      %li.active Edit
    %ul.nav.nav-tabs
      %li.icon.show_member_link{:rel => "", :title => ""}
        = link_to admin_product_path(@product.id) do
          .glyphicon.glyphicon-eye-open
          %span Show
      %li.icon.edit_member_link.active{:rel => "", :title => ""}
        = link_to edit_admin_product_path(@product.id) do
          .glyphicon.glyphicon-pencil
          %span Edit
      %li.icon.delete_member_link{:rel => "", :title => ""}
        = link_to admin_product_path(@product.id), method: :delete, data: { confirm: 'Are you sure?' } do
          .glyphicon.glyphicon-remove
          %span Delete
    %br
    .col-xs-12.col-sm-12.col-md-11.col-lg-10
      = form_tag(admin_product_path, method: :put, multipart: true, id: 'edit_product', class: 'form-horizontal denser') do
        %fieldset
          %h4
            Basic info
          .form-group.control-group.string_type.name_field
            .col-sm-6
              %label.control-label Name*
              .controls
                = text_field_tag "product[name]", @product.name, class: 'form-control', :required => "required", :size => "50"
            .col-sm-6
              %label.control-label Measurement*
              .controls
                = text_field_tag "product[measurement]", @product.measurement, class: 'form-control', :required => "required", :size => "50"
            .clearfix
          .form-group.control-group.string_type.name_field
            .col-sm-6
              %label.control-label Subcategory
              .controls
                = select_tag "product[subcategory_id]", options_from_collection_for_select(@subcategories, "id", "name", @product.subcategory_id), class: 'form-control'
            .col-sm-6
              %label.control-label Supplier
              .controls
                = select_tag "product[supplier_id]", options_from_collection_for_select(@suppliers, "id", "name", @product.supplier_id), class: 'form-control'
            .clearfix
          .form-group.control-group.string_type.name_field
            .col-sm-6
              %label.control-label Image
              .controls
                = image_tag @product.photo.url(:thumb), class: 'img-thumbnail'
                = file_field_tag "product[photo]"
            .col-sm-6
              %label.control-label Description*
              .controls
                = text_area_tag "product[description]", @product.description, class: 'form-control', :required => "required", :rows => "7"
            .clearfix
          %hr
          %h4
            Characteristics
          - if @product.characteristics.count > 0
            .form-group.control-group.string_type.name_field
              .col-sm-6
                %label.control-label Characteristic*
              .col-sm-6
                %label.control-label Value*
              .clearfix
              - @product.characteristics.each do |c|
                .characteristic-cart
                  .col-sm-6
                    .controls
                      .col-xs-10.col-sm-10.padding-0= text_field_tag "edit_characteristic[#{c.id}]", c.name, class: ' form-control', :required => "required", :size => "50"
                      .col-xs-1.col-sm-1
                        = link_to '', admin_remove_characteristic_path(characteristic_id: c.id), remote: true
                        .btn.btn-danger.ajax-delete-characteristic
                          .glyphicon.glyphicon-remove
                      .clearfix
                    %br
                  .col-sm-6
                    - c.values.each do |v|
                      .value-cart.controls
                        .col-xs-10.col-sm-10.padding-0= text_field_tag "edit_value[#{v.id}]", v.name, class: 'form-control', :required => "required", :size => "50"
                        .col-xs-1.col-sm-1
                          = link_to admin_remove_value_path(value_id: v.id), remote: true, class: 'ajax-delete-value' do
                            .btn.btn-warning
                              .glyphicon.glyphicon-remove
                        .clearfix
                        %br
                  .clearfix

          #product_characteristics_field.form-group.control-group.string_type.input_fields_characteristic
            = hidden_field_tag :count_of_characteristics, '', id: 'count-of-characteristics'
            %div{class: 'qwerty', "data-item" => "1", style: "margin-bottom: 15px;" }
              .col-sm-6
                %label.control-label{:for => "product_description"} Characteristics
                .controls
                  = text_field_tag "characteristic[1]", '', class: 'form-control'
              .col-sm-5.input_fields_value
                %label.control-label{:for => "product_description"} Values
                .input-group{style: "margin-bottom: 15px;" }
                  %input.form-control{:type => "text", name: "value[1_1]", "data-item" => '1'}/
                  %span.input-group-addon.add_value_button
                    .glyphicon.glyphicon-plus
              %span.col-sm-1.padding-0.add_characteristic_button{style: "margin-top: 27px;"}
                .btn.btn-default
                  .glyphicon.glyphicon-plus
              .characteristic-input
              .clearfix
          .clearfix
          %br
        .form-group.form-actions
          .col-sm-10
            %button.btn.btn-primary{"data-disable-with" => "Updating", :name => "_save", :type => "submit"}
              %i.icon-white.icon-ok
              Update
            %span.extra_buttons
              = link_to admin_products_path do
                .btn.btn-default
                  %i.icon-remove
                  Cancel
          .clearfix

app/views/admin/products/index.html.haml
= render 'partials/header'
= render 'admin/sidebar'
.col-xs-12.col-sm-8.col-md-8.col-lg-9
  %title Site Administration | Supply Admin
  .page-header
    %h1 List of Products
  %ol.breadcrumb
    %li= link_to 'Dashboard', admin_home_path
    %li.active Products
  %ul.nav.nav-tabs
    %li.icon.dashboard_root_link.active{:rel => "", :title => ""}
      = link_to admin_products_path, class: 'pjax' do
        .glyphicon.glyphicon-list
        %span Products
    %li.icon.dashboard_root_link{:rel => "", :title => ""}
      = link_to new_admin_product_path, class: 'pjax' do
        .glyphicon.glyphicon-plus
        %span Add new
  %table.table.table-condensed.table-striped
    %table#products-table.table
      %thead
        %tr
          %th.header.pjax.name_field.string_type Name
          %th.header.pjax.image_field.paperclip_type Photo
          %th.header.pjax.name_field.string_type Subcategory
          %th.header.pjax.name_field.string_type Supplier
          %th.last.shrink
.clearfix

app/views/admin/products/new.html.haml
= render 'partials/header'
= render 'admin/sidebar'
.col-xs-12.col-sm-8.col-md-8.col-lg-9
  .content{"data-pjax-container" => ""}
    .page-header
      %h1 New Product
    %ol.breadcrumb
      %li.false
        = link_to 'Dashboard', admin_home_path, class: 'pjax'
      %li.false
        = link_to 'Products', admin_products_path, class: 'pjax'
      %li.active New
    %ul.nav.nav-tabs
      %li.icon.dashboard_root_link{:rel => "", :title => ""}
        = link_to admin_products_path, class: 'pjax' do
          .glyphicon.glyphicon-list
          %span Products
      %li.icon.dashboard_root_link.active{:rel => "", :title => ""}
        = link_to new_admin_product_path, class: 'pjax' do
          .glyphicon.glyphicon-plus
          %span Add new
    %br
    = form_tag(admin_products_path, method: :post, multipart: true, id: 'new_product', class: 'form-horizontal denser') do
      %fieldset
        .col-xs-12.col-sm-12.col-md-12.col-lg-12
          .form-group.control-group.string_type.name_field
            .col-sm-5
              %label.control-label Name*
              .controls
                = text_field_tag "product[name]", '', class: 'form-control', :required => "required", :size => "50"
            .col-sm-5
              %label.control-label Measurement*
              .controls
                = text_field_tag "product[measurement]", '', class: 'form-control', :required => "required", :size => "50"
            .clearfix
          .form-group.control-group.string_type.name_field
            .col-sm-5
              %label.control-label Subcategory
              .controls
                = select_tag "product[subcategory_id]", options_from_collection_for_select(@subcategories, "id", "name"), class: 'form-control'
            .col-sm-5
              %label.control-label{:for => "subcategory_name"} Supplier
              .controls
                = select_tag "product[supplier_id]", options_from_collection_for_select(@suppliers, "id", "name"), class: 'form-control'
            .clearfix
          .form-group.control-group.paperclip_type.image_field
            .col-sm-5
              %label.control-label Description
              .controls
                = text_area_tag "product[description]", '', class: 'form-control', :required => "required", :rows => "7"
            .col-sm-5
              %label.control-label Image
              .controls
                .toggle
                  = file_field_tag "product[photo]"
            .clearfix
        .clerfix
        .col-xs-12.col-sm-12.col-md-11.col-lg-10
          #product_characteristics_field.form-group.control-group.string_type.input_fields_characteristic
            = hidden_field_tag :count_of_characteristics, '', id: 'count-of-characteristics'
            %div{class: 'qwerty', "data-item" => "1", style: "margin-bottom: 15px;" }
              .col-sm-6
                %label.control-label{:for => "product_description"} Characteristics
                .controls
                  = text_field_tag "characteristic[1]", '', class: 'form-control'
              .col-sm-5.input_fields_value
                %label.control-label{:for => "product_description"} Values
                .input-group{style: "margin-bottom: 15px;" }
                  %input.form-control{:type => "text", name: "value[1_1]", "data-item" => '1'}/
                  %span.input-group-addon.add_value_button
                    .glyphicon.glyphicon-plus
              %span.col-sm-1.padding-0.add_characteristic_button{style: "margin-top: 27px;"}
                .btn.btn-default
                  .glyphicon.glyphicon-plus
              .clearfix
          #product_characteristics_field.form-group.control-group.string_type.name_field
            .col-sm-5
              %button.btn.btn-primary{"data-disable-with" => "Saving", :name => "_save", :type => "submit"}
                %i.icon-white.icon-ok
                Save
              %span.extra_buttons
                = link_to admin_products_path do
                  .btn.btn-default
                    %i.icon-remove
                    Cancel
            .clearfix
.clearfix

app/views/admin/products/show.html.haml
= render 'partials/header'
= render 'admin/sidebar'
.col-xs-12.col-sm-8.col-md-8.col-lg-9  
  .content{"data-pjax-container" => ""}
    .page-header
      %h1 Details for Product #{@product.name}
    %ol.breadcrumb
      %li.false
        = link_to 'Dashboard', admin_home_path, class: 'pjax'
      %li.false
        = link_to 'Products', admin_products_path, class: 'pjax'
      %li.active= @product.name
    %ul.nav.nav-tabs
      %li.icon.show_member_link.active{:rel => "", :title => ""}
        = link_to admin_product_path(@product.id) do
          .pjax
            .glyphicon.glyphicon-eye-open
            %span Show
      %li.icon.edit_member_link{:rel => "", :title => ""}
        = link_to edit_admin_product_path(@product.id) do
          .pjax
            .glyphicon.glyphicon-pencil
            %span Edit
      %li.icon.delete_member_link{:rel => "", :title => ""}
        = link_to admin_product_path(@product.id), method: :delete, data: { confirm: 'Are you sure?' } do
          .pjax
            .glyphicon.glyphicon-remove
            %span Delete
    .fieldset
      %h4
        Basic info
      %dl
        .col-xs-12.col-sm-12.col-md-6.col-lg-6
          %dt
            %span.label.label-info.name_field.string_type
              Name
          %dd.well
            = @product.name
          %dt
            %span.label.label-info.name_field.string_type
              Subcategory
          %dd.well
            = link_to @product.subcategory.name, admin_subcategory_path(@product.subcategory.id)
          %dt
            %span.image_field.label.label-info.paperclip_type
              Image
          %dd.well
            = link_to @product.photo.url, :target => "_blank" do
              = image_tag @product.photo.url(:medium), class: 'img-thumbnail'
        .col-xs-12.col-sm-12.col-md-6.col-lg-6
          %dt
            %span.label.label-info.name_field.string_type
              Measurement
          %dd.well
            = @product.measurement
          %dt
            %span.label.label-info.name_field.string_type
              Supplier
          %dd.well
            = @product.supplier.name
          %dt
            %span.image_field.label.label-info.paperclip_type
              Description
          %dd.well
            = @product.description
        .clearfix
        .col-xs-12.col-sm-12.col-md-12.col-lg-12
          %dt
          %span.has_many_association_type.label.label-info.subcategories_field
            Characteristics
          %dd.well
            - get_characteristics(@product.characteristics).each do |c|
              %dl.col-xs-12.col-sm-6.col-md-4.col-lg-3
                %dt #{c.name}:
                - get_values(c.values).each do |v|
                  %dd - #{v.name}
            .clearfix